# Generated by Django 2.2.12 on 2020-07-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentMethodTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OMProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerforationMethodTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenCoatingTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenFittingTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenFormTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenMakerTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenMaterialTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenModelTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenNumberTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenPlacementTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bodyqualitytype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingcoatingterm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingformterm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingmaterialterm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filtrationmaterialterm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sealingmaterialterm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sealingtypeterm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilitytype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wellstatustypeterm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sealing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casing_left', models.ManyToManyField(blank=True, help_text='Casing left after plugging.', null=True, related_name='casing_left', to='gwml2.CasingComponent', verbose_name='casingLeft')),
                ('casing_slit', models.ManyToManyField(blank=True, help_text='Casing slit opposing water bearing zones before plugging.', null=True, related_name='casing_slit', to='gwml2.CasingComponent', verbose_name='casingSlit')),
                ('sealing_element', models.ManyToManyField(blank=True, help_text='Relation between a seal and its parts.', null=True, to='gwml2.SealingComponent', verbose_name='sealingElement')),
                ('sealing_grouting_placement_method', models.ForeignKey(blank=True, help_text='Method of placing the sealing grouting.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.OMProcess', verbose_name='sealingGroutingPlacementMethod')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_component', models.ForeignKey(blank=True, help_text='A screen part is a type of construction component.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.ConstructionComponent', verbose_name='ConstructionComponent')),
                ('screen_attachment_method', models.ForeignKey(blank=True, help_text='Screen attachment method. E.g. telescoped, oncasing, on riser pipe, neoprene (K) packer, Lead packer, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.AttachmentMethodTerm', verbose_name='screenAttachmentMethod')),
                ('screen_coating', models.ForeignKey(blank=True, help_text='Thin outer layer applied to the screen. E.g.galvanized, stainless, copper bearing, low carbon, black, porous, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.ScreenCoatingTerm', verbose_name='screenCoating')),
                ('screen_external_diameter', models.OneToOneField(blank=True, help_text='External screen diameter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_external_diameter', to='gwml2.Quantity', verbose_name='screenExternalDiameter')),
                ('screen_fitting', models.ForeignKey(blank=True, help_text='The screen fitting (from the bottom). E.g. bail,open, plug, tail pipe, washdown, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.ScreenFittingTerm', verbose_name='screenFitting')),
                ('screen_form', models.ForeignKey(blank=True, help_text='Form of the screen. E.g. slotted casing,perforated casing, bridge slot casing, wire wrapor continuous slot, wire mesh, shutter orlouvered, well point, tube, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.ScreenFormTerm', verbose_name='screenForm')),
                ('screen_hole_size', models.OneToOneField(blank=True, help_text='Size of the slots or perforations of the screen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_hole_size', to='gwml2.Quantity', verbose_name='screenHoleSize')),
                ('screen_internal_diameter', models.OneToOneField(blank=True, help_text='Internal screen diameter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_internal_diameter', to='gwml2.Quantity', verbose_name='screenInternalDiameter')),
                ('screen_make', models.ForeignKey(blank=True, help_text='Make of the screen.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.ScreenMakerTerm', verbose_name='screenMake')),
                ('screen_material', models.ForeignKey(blank=True, help_text='Material that makes up the screen. E.g. metal,steel, iron, copper, brass, bronze, everdur,Armco metal, veriperm, stone, plastic, PVC,ABS, Fibreglass, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.ScreenMaterialTerm', verbose_name='screenMaterial')),
                ('screen_model', models.ForeignKey(blank=True, help_text='Model of the screen.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.ScreenModelTerm', verbose_name='screenModel')),
                ('screen_number', models.ForeignKey(blank=True, help_text='Screen number corresponds to hole size and isgiven in 0.001 inch. The value is expressed as an alphanumeric code.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.ScreenNumberTerm', verbose_name='screenNumber')),
                ('screen_perforation_method', models.ForeignKey(blank=True, help_text='Method used for perforating the screen. E.g.drill, grinder, axe / chisel, machine, saw, torch,other, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.PerforationMethodTerm', verbose_name='screenPerforationMethod')),
                ('screen_placement', models.ForeignKey(blank=True, help_text='Screen placement method. E.g. bail down, pullback, jetted, washed down, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.ScreenPlacementTerm', verbose_name='screenPlacement')),
                ('screen_wall_thickness', models.OneToOneField(blank=True, help_text='Thickness of the screen wall.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_wall_thickness', to='gwml2.Quantity', verbose_name='screenWallThickness')),
            ],
        ),
    ]
