# Generated by Django 2.2.12 on 2020-07-01 04:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingCoatingTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasingFormTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasingMaterialTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_component', models.ForeignKey(blank=True, db_column='from', help_text='Position of the top (nearest to the borehole start) of the component.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_component_from', to='groundwater.Quantity')),
                ('to_component', models.ForeignKey(blank=True, db_column='to', help_text='Position of the bottom (farthest to the borehole start) of the component.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_component_to', to='groundwater.Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='FiltrationMaterialTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='borehole',
            name='bhole_date_of_drilling',
            field=models.DateField(help_text='Date of drilling.', null=True, verbose_name='bholeDateOfDrilling'),
        ),
        migrations.AlterField(
            model_name='borehole',
            name='bhole_nominal_diameter',
            field=models.ForeignKey(blank=True, help_text='Diameter of the borehole.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.Quantity', verbose_name='bholeNominalDiameter'),
        ),
        migrations.AlterField(
            model_name='gwwell',
            name='gw_well_construction',
            field=models.ForeignKey(blank=True, help_text='Construction details for a well.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.Borehole', verbose_name='gwWellConstruction'),
        ),
        migrations.AlterField(
            model_name='gwwell',
            name='gw_well_contribution_zone',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='The area or volume surrounding a pumping wellor other discharge site that encompasses all areasand features that supply groundwater to the wellor discharge site.', null=True, srid=4326, verbose_name='gwWellContributionZone'),
        ),
        migrations.AlterField(
            model_name='gwwell',
            name='gw_well_location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Surface location of the well.', srid=4326, verbose_name='gwWellLocation'),
        ),
        migrations.AlterField(
            model_name='gwwell',
            name='gw_well_name',
            field=models.TextField(help_text='Name or ID of the well.', verbose_name='gwWellName'),
        ),
        migrations.AlterField(
            model_name='gwwell',
            name='gw_well_static_water_depth',
            field=models.ForeignKey(blank=True, help_text='Depth of the fluid body (e.g. piezometric level).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.Quantity', verbose_name='gwWellStaticWaterDepth'),
        ),
        migrations.AlterField(
            model_name='gwwell',
            name='gw_well_status',
            field=models.ForeignKey(blank=True, help_text='Status of the well, Can be new, unfinished, reconditioned, deepened, not in use, standby,unknown, abandoned dry, abandonedinsufficient, abandoned quality. (gwml1)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.WellStatusTypeTerm', verbose_name='gwWellStatus'),
        ),
        migrations.AlterField(
            model_name='gwwell',
            name='gw_well_total_length',
            field=models.FloatField(blank=True, help_text='Total length of the well from reference elevation.', null=True, verbose_name='gwWellTotalLength'),
        ),
        migrations.AlterField(
            model_name='sealingcomponent',
            name='sealing_material',
            field=models.ForeignKey(blank=True, help_text='Material used in the sealing component of a water well. E.g. formation packer, welded ring, shale trap, drive shoe, driven casing, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.SealingMaterialTerm', verbose_name='sealingMaterial'),
        ),
        migrations.AlterField(
            model_name='sealingcomponent',
            name='sealing_type',
            field=models.ForeignKey(blank=True, help_text='Type of sealing. E.g. annular sealing, plugging, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.SealingTypeTerm', verbose_name='sealingType'),
        ),
        migrations.CreateModel(
            name='FiltrationComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_component', models.OneToOneField(blank=True, help_text='A filtration part is a type of construction component', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.ConstructionComponent', verbose_name='ConstructionComponent')),
                ('filter_grain_size', models.ForeignKey(blank=True, help_text='Size of the particles of the filtration material.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.Quantity', verbose_name='filterGrainSize')),
                ('filter_material', models.ForeignKey(blank=True, help_text='Material used in the filtration device. E.g. gravel,pit run, silica sand, washed sand, crushed rock, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.FiltrationMaterialTerm', verbose_name='FiltrationMaterialTerm')),
            ],
        ),
        migrations.CreateModel(
            name='CasingComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casing_coating', models.ForeignKey(blank=True, help_text='Coating applied to the casing. E.g. galvanized,stainless, mild, low carbon, copper bearing,black, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_coating', to='groundwater.CasingMaterialTerm', verbose_name='casingCoating')),
                ('casing_external_diameter', models.ForeignKey(blank=True, help_text='External diameter of the casing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_external_diameter', to='groundwater.Quantity', verbose_name='casingExternalDiameter')),
                ('casing_form', models.ForeignKey(blank=True, help_text='Form of material used in the casing. E.g.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_form', to='groundwater.CasingFormTerm', verbose_name='casingForm')),
                ('casing_internal_diameter', models.ForeignKey(blank=True, help_text='Internal diameter of the casing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_internal_diameter', to='groundwater.Quantity', verbose_name='casingInternalDiameter')),
                ('casing_material', models.ForeignKey(blank=True, help_text='Material in which the casing is made. E.g. metal, steel, iron, concrete, wood, brick, plastic, teflon,PVC, ABS, fibreglass, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_material', to='groundwater.CasingMaterialTerm', verbose_name='casingMaterial')),
                ('casing_wall_thickness', models.ForeignKey(blank=True, help_text='Thickness of the wall of the casing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_wall_thickness', to='groundwater.Quantity', verbose_name='casingWallThickness')),
            ],
        ),
    ]
