# Generated by Django 2.2.12 on 2020-07-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0003_auto_20200702_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('casing_element', models.ManyToManyField(blank=True, help_text='Relation between a casing and its parts.', null=True, to='gwml2.CasingComponent', verbose_name='casingElement')),
            ],
        ),
        migrations.CreateModel(
            name='Filtration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('filter_element', models.ManyToManyField(blank=True, help_text='Relation between a filtration device and its parts.', null=True, to='gwml2.FiltrationComponent', verbose_name='filterElement')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('screen_element', models.ManyToManyField(blank=True, help_text='Relation between a screen and its parts.', null=True, to='gwml2.ScreenComponent', verbose_name='screenElement')),
            ],
        ),
        migrations.CreateModel(
            name='WellConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('casing', models.ForeignKey(blank=True, help_text='A casing is a type of well construction entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.Casing', verbose_name='Casing')),
                ('filtration', models.ForeignKey(blank=True, help_text='A sealing is a type of well construction entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.Filtration', verbose_name='Filtration')),
                ('screen', models.ForeignKey(blank=True, help_text='A screen is a type of well construction entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.Screen', verbose_name='Screen')),
                ('sealing', models.ForeignKey(blank=True, help_text='A sealing is a type of well construction entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.Sealing', verbose_name='Sealing')),
            ],
        ),
    ]
