# Generated by Django 2.2.12 on 2020-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0003_view_well_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='drilling',
            name='year_of_drilling',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
