# Generated by Django 2.2.12 on 2020-07-01 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0003_auto_20200701_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borehole',
            name='bhole_nominal_diameter',
            field=models.OneToOneField(blank=True, help_text='Diameter of the borehole.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.Quantity', verbose_name='bholeNominalDiameter'),
        ),
        migrations.AlterField(
            model_name='casingcomponent',
            name='casing_external_diameter',
            field=models.OneToOneField(blank=True, help_text='External diameter of the casing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_external_diameter', to='groundwater.Quantity', verbose_name='casingExternalDiameter'),
        ),
        migrations.AlterField(
            model_name='casingcomponent',
            name='casing_internal_diameter',
            field=models.OneToOneField(blank=True, help_text='Internal diameter of the casing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_internal_diameter', to='groundwater.Quantity', verbose_name='casingInternalDiameter'),
        ),
        migrations.AlterField(
            model_name='casingcomponent',
            name='casing_wall_thickness',
            field=models.OneToOneField(blank=True, help_text='Thickness of the wall of the casing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_wall_thickness', to='groundwater.Quantity', verbose_name='casingWallThickness'),
        ),
        migrations.AlterField(
            model_name='constructioncomponent',
            name='from_component',
            field=models.OneToOneField(blank=True, db_column='from', help_text='Position of the top (nearest to the borehole start) of the component.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_component_from', to='groundwater.Quantity'),
        ),
        migrations.AlterField(
            model_name='constructioncomponent',
            name='to_component',
            field=models.OneToOneField(blank=True, db_column='to', help_text='Position of the bottom (farthest to the borehole start) of the component.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_component_to', to='groundwater.Quantity'),
        ),
        migrations.AlterField(
            model_name='filtrationcomponent',
            name='construction_component',
            field=models.ForeignKey(blank=True, help_text='A filtration part is a type of construction component', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.ConstructionComponent', verbose_name='ConstructionComponent'),
        ),
        migrations.AlterField(
            model_name='filtrationcomponent',
            name='filter_grain_size',
            field=models.OneToOneField(blank=True, help_text='Size of the particles of the filtration material.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.Quantity', verbose_name='filterGrainSize'),
        ),
    ]
