# Generated by Django 2.2.12 on 2020-10-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0003_view_well_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='termmeasurementparameter',
            name='units',
            field=models.ManyToManyField(blank=True, null=True, to='gwml2.Unit'),
        ),
    ]
