# Generated by Django 2.2.12 on 2020-10-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0004_termmeasurementparameter_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organisation',
            },
        ),
    ]
