# Generated by Django 2.2.12 on 2020-10-28 09:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0006_auto_20201023_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='editors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='organisation',
            name='viewers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='constructionstructure',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gwml2.Construction'),
        ),
        migrations.AlterField(
            model_name='waterstrike',
            name='drilling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gwml2.Drilling'),
        ),
    ]
