# Generated by Django 2.2.12 on 2020-11-02 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0006_auto_20201023_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('filters', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('progress', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Download Session',
                'verbose_name_plural': 'Download Sessions',
                'db_table': 'download_session',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'Quantity', 'verbose_name_plural': 'Quantities'},
        ),
        migrations.AlterModelOptions(
            name='termwellstatus',
            options={'ordering': ['order'], 'verbose_name': 'Term well status', 'verbose_name_plural': 'Term well status'},
        ),
        migrations.AlterField(
            model_name='constructionstructure',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gwml2.Construction'),
        ),
        migrations.AlterField(
            model_name='waterstrike',
            name='drilling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gwml2.Drilling'),
        ),
    ]
