# Generated by Django 2.2.12 on 2020-07-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0006_elevation_elevationmeasurementmethodtype_elevationtypeterm_positionalaccuracytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCharacteristicTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentTypeTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField(help_text='Date of installation of the equipment.', null=True, verbose_name='installationDate')),
                ('characteristics', models.ManyToManyField(blank=True, help_text='General characteristics of the equipment.', null=True, to='gwml2.EquipmentCharacteristicTerm', verbose_name='Characteristics')),
                ('equipment_type', models.ForeignKey(blank=True, help_text='Type of equipment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.EquipmentTypeTerm', verbose_name='EquipmentType')),
            ],
        ),
        migrations.AddField(
            model_name='borehole',
            name='installed_equipment',
            field=models.ManyToManyField(blank=True, help_text='Relation designating the equipment installed in a borehole.', null=True, to='gwml2.Equipment', verbose_name='installedEquipment'),
        ),
    ]
