# Generated by Django 2.2.12 on 2020-07-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0007_auto_20200702_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TMPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='startTime')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='endTime')),
            ],
        ),
        migrations.AddField(
            model_name='gwgeologylog',
            name='resultQuality',
            field=models.TextField(blank=True, help_text='The quality of the result', null=True, verbose_name='resultQuality'),
        ),
        migrations.RemoveField(
            model_name='gwgeologylog',
            name='parameter',
        ),
        migrations.AlterField(
            model_name='gwgeologylog',
            name='phenomenon_time',
            field=models.DateTimeField(blank=True, help_text='Reflects the time that the result applies to the property', null=True, verbose_name='phenomenonTime'),
        ),
        migrations.AlterField(
            model_name='gwgeologylog',
            name='result_time',
            field=models.DateTimeField(blank=True, help_text='The time at which the value has been obtained or became available', null=True, verbose_name='resultTime'),
        ),
        migrations.CreateModel(
            name='OMObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenomenon_time', models.DateTimeField(blank=True, help_text='Reflects the time that the result applies to the property', null=True, verbose_name='phenomenonTime')),
                ('result_time', models.DateTimeField(blank=True, help_text='The time at which the value has been obtained or became available', null=True, verbose_name='resultTime')),
                ('resultQuality', models.TextField(blank=True, help_text='The quality of the result', null=True, verbose_name='resultQuality')),
                ('parameter', models.ManyToManyField(blank=True, help_text='This shall describe an arbitrary event-specific parameter. This might be an environmental parameter, an instrument setting or input, or an event-specific sampling parameter that is not tightly bound to either the feature-of-interest or to the observation procedure (6.2.2.10).', null=True, to='gwml2.NamedValue', verbose_name='parameter')),
                ('valid_time', models.ForeignKey(blank=True, help_text='The time during which the value is usable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.TMPeriod', verbose_name='validTime')),
            ],
        ),
        migrations.AddField(
            model_name='gwgeologylog',
            name='valid_time',
            field=models.ForeignKey(blank=True, help_text='The time during which the value is usable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.TMPeriod', verbose_name='validTime'),
        ),
        migrations.AddField(
            model_name='gwgeologylog',
            name='parameter',
            field=models.ManyToManyField(blank=True, help_text='This shall describe an arbitrary event-specific parameter. This might be an environmental parameter, an instrument setting or input, or an event-specific sampling parameter that is not tightly bound to either the feature-of-interest or to the observation procedure (6.2.2.10).', null=True, to='gwml2.NamedValue', verbose_name='parameter'),
        ),
    ]
