# Generated by Django 2.2.12 on 2020-11-02 19:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0007_auto_20201102_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='admins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='organisation',
            name='editors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='organisation',
            name='viewers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='well',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.Organisation'),
        ),
    ]
