# Generated by Django 2.2.12 on 2020-10-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0007_auto_20201028_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.Organisation'),
        ),
    ]
