# Generated by Django 2.2.12 on 2020-11-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0008_auto_20201102_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drilling',
            name='total_depth',
        ),
    ]
