# Generated by Django 2.2.12 on 2020-07-02 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0008_auto_20200702_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='GWStringType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpringCauseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpringPersistenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GWSpring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_spring_name', models.TextField(help_text='Name or ID of the spring.', verbose_name='gwSpringName')),
                ('gw_spring_location', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Geometry / position of the spring.', null=True, srid=4326, verbose_name='gwSpringLocation')),
                ('gw_spring_construction', models.TextField(blank=True, help_text='Spring construction details, if any.', null=True, verbose_name='gwSpringConstruction')),
                ('gwSpringPersistence', models.ForeignKey(blank=True, help_text='The periodicity of the spring e.g. ephemeral, perennial, intermittent, seasonal, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.SpringPersistenceType', verbose_name='gwSpringPersistence')),
                ('gw_spring_body', models.ManyToManyField(blank=True, help_text='The fluid body being depleted by the spring.', null=True, to='gwml2.GWFluidBody', verbose_name='gwSpringBody')),
                ('gw_spring_cause_type', models.ForeignKey(blank=True, help_text='Type of spring e.g. mineral, thermal, saline, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.SpringCauseType', verbose_name='gwSpringCauseType')),
                ('gw_spring_licence', models.ManyToManyField(blank=True, help_text='Any licence relating to the spring.', null=True, to='gwml2.GWLicence', verbose_name='gwSpringLicence')),
                ('gw_spring_reference_elevation', models.ManyToManyField(help_text='Description of the accuracy of the elevation measurement.', to='gwml2.Elevation', verbose_name='gwSpringReferenceElevation')),
                ('gw_spring_type', models.ForeignKey(blank=True, help_text='Type of spring e.g. mineral, thermal, saline, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.GWStringType', verbose_name='gwSpringType')),
            ],
        ),
    ]
