# Generated by Django 2.2.12 on 2020-11-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0009_remove_drilling_total_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='uploader',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='upload_file',
            field=models.FileField(null=True, upload_to='gwml2/upload/'),
        ),
    ]
