# Generated by Django 2.2.12 on 2020-07-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0009_gwspring_gwstringtype_springcausetype_springpersistencetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentCharacteristicTerm',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='characteristics',
            field=models.ManyToManyField(blank=True, help_text='General characteristics of the equipment.', null=True, to='gwml2.NamedValue', verbose_name='Characteristics'),
        ),
    ]
