# Generated by Django 2.2.12 on 2020-11-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0010_auto_20201104_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadsession',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
