# Generated by Django 2.2.12 on 2020-07-02 11:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0010_auto_20200702_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPersistenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GWDischarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_rate', models.ForeignKey(help_text='Volumetric flow rate of water that goes out', on_delete=django.db.models.deletion.CASCADE, to='gwml2.Quantity', verbose_name='FlowRateDischarge')),
            ],
        ),
        migrations.CreateModel(
            name='GWIntraFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_flow_location', django.contrib.gis.db.models.fields.MultiPointField(help_text='The location where a fluid is flowing within a feature.', srid=4326, verbose_name='GwFlowLocation')),
            ],
        ),
        migrations.CreateModel(
            name='WaterFlowProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GWRecharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_rate', models.ForeignKey(help_text='Volumetric flow rate of water that enters', on_delete=django.db.models.deletion.CASCADE, to='gwml2.Quantity', verbose_name='FlowRateRecharge')),
            ],
        ),
        migrations.CreateModel(
            name='GWInterFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_flow_location', django.contrib.gis.db.models.fields.MultiPointField(help_text='The location at which water is being transferred from one feature into another.', srid=4326, verbose_name='GWFlowLocation')),
                ('gw_discharge', models.ManyToManyField(blank=True, help_text='Discharge is a type of interflow in which fluid exits a feature.', null=True, to='gwml2.GWDischarge', verbose_name='GWDischarge')),
                ('gw_recharge', models.ManyToManyField(blank=True, help_text='Recharge is a type of interflow in which fluid enters a feature.', null=True, to='gwml2.GWRecharge', verbose_name='GWRecharge')),
            ],
        ),
        migrations.CreateModel(
            name='GWFlowSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_flow_path', django.contrib.gis.db.models.fields.GeometryField(help_text='The path of flow of a fluid through a container.', srid=4326, verbose_name='GWFlowPath')),
                ('gw_part_of_system_flow', models.ForeignKey(blank=True, help_text='Relates a flow system part to a flow system whole.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.GWFlowSystem')),
            ],
        ),
        migrations.CreateModel(
            name='GWFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_flow_time', models.TextField(blank=True, help_text='Refers to the duration, instant or interval of the flow (actual time, not observation time). E.g. "yearly", "summer", "2009" or "2009-2011".', null=True, verbose_name='GWFlowTime')),
                ('gw_flow_persistence', models.OneToOneField(blank=True, help_text='The regularity of flow occurrence, e.g. ephemeral, intermittent, perennial, seasonal. After http://inspire.ec.europa.eu/codeList/WaterPersist enceValue/ (INSPIRE, 2013).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.FlowPersistenceType', verbose_name='gwFlowPersistence')),
                ('gw_flow_process', models.ForeignKey(blank=True, help_text='The process causing the flow, e.g. evapotranspiration, evaporation, transpiration, runoff, baseflow, pumping, infiltration, injection, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.WaterFlowProcess', verbose_name='GWFlowProcess')),
                ('gw_flow_system', models.ForeignKey(blank=True, help_text='Relates a flow system to the individual flowsthat comprise the system. Flows are atomic entities that cannot have parts, but which form parts of flow systems', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.GWFlowSystem', verbose_name='GWFlowSystem')),
                ('gw_flow_velocity', models.OneToOneField(blank=True, help_text='Measure of water volume per unit of time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gw_flow_velocity', to='gwml2.Quantity', verbose_name='GWFlowVelocity')),
                ('gw_flow_volume_rate', models.OneToOneField(blank=True, help_text='Measure of water quantity per time period with uom.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gw_flow_volume_rate', to='gwml2.Quantity', verbose_name='GWFlowVolumeRate')),
            ],
        ),
    ]
