# Generated by Django 2.2.12 on 2020-11-09 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0011_downloadsession_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUUID',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'user_uuid',
            },
        ),
    ]
