# Generated by Django 2.2.12 on 2020-07-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0011_flowpersistencetype_gwdischarge_gwflow_gwflowsystem_gwinterflow_gwintraflow_gwrecharge_waterflowproc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwflow',
            name='gw_flow_persistence',
            field=models.ForeignKey(blank=True, help_text='The regularity of flow occurrence, e.g. ephemeral, intermittent, perennial, seasonal. After http://inspire.ec.europa.eu/codeList/WaterPersist enceValue/ (INSPIRE, 2013).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.FlowPersistenceType', verbose_name='gwFlowPersistence'),
        ),
    ]
