# Generated by Django 2.2.12 on 2020-11-17 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0013_view_well_information_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionstructure',
            options={'ordering': ('top_depth__value',)},
        ),
        migrations.AlterModelOptions(
            name='stratigraphiclog',
            options={'ordering': ('top_depth__value',)},
        ),
        migrations.AddField(
            model_name='well',
            name='time_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
