# Generated by Django 2.2.12 on 2020-07-03 07:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0015_auto_20200703_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GWMonitoringSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_site_name', models.TextField(blank=True, help_text='Name (or identifier) of the monitoring site.', null=True, verbose_name='gwSiteName')),
                ('gw_site_location', django.contrib.gis.db.models.fields.PointField(help_text='Spatial location of the site.', srid=4326, verbose_name='gwSiteLocation')),
                ('gw_site_reference_elevation', models.ManyToManyField(help_text='Reference elevation for all observations at the site, e.g. ground elevation, casing elevation. This can differ from the host feature elevation, or be more specific.', to='gwml2.Elevation', verbose_name='gwSiteReferenceElevation')),
                ('gw_site_type', models.ForeignKey(blank=True, help_text='Type of monitoring site, e.g. well, gauging station, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.SiteType', verbose_name='gwSiteType')),
            ],
        ),
    ]
