# Generated by Django 2.2.12 on 2020-11-23 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0015_auto_20201117_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='time_updated',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='well',
            name='affiliate_organisations',
            field=models.ManyToManyField(blank=True, null=True, related_name='well_affiliate_organisations', to='gwml2.Organisation'),
        ),
        migrations.AddField(
            model_name='well',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='last_edited_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='well',
            name='last_edited_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
