# Generated by Django 2.2.12 on 2020-07-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0016_gwmonitoringsite_sitetype'),
        ('gwml2', '0016_documentcitation_environmentaldomaintypeterm_gwmanagementarea_gwyield_managementareatypeterm_special'),
    ]

    operations = [
    ]
