# Generated by Django 2.2.12 on 2020-11-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0016_auto_20201123_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='category',
            field=models.CharField(blank=True, choices=[('well_upload', 'well_upload'), ('well_monitoring_upload', 'well_monitoring_upload')], default='', max_length=50),
        ),
    ]
