# Generated by Django 2.2.12 on 2020-11-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0017_auto_20201124_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormHelpText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=256)),
                ('field', models.CharField(max_length=256)),
                ('help_text', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'form_help_text',
                'unique_together': {('form', 'field')},
            },
        ),
    ]
