# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0018_auto_20200703_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='GWVoidUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_hydrogeo_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwml2.GWHydrogeoUnit', verbose_name='GWHydrogeoUnit')),
                ('gw_unit_void_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwml2.GWUnitVoidProperty', verbose_name='GWUnitVoidProperty')),
            ],
        ),
        migrations.RemoveField(
            model_name='gwhydrogeovoid',
            name='gw_void_metadata',
        ),
        migrations.AddField(
            model_name='gwhydrogeovoid',
            name='gw_void_metadata',
            field=models.ForeignKey(blank=True, help_text='Metadata for the void.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.GWMetadata', verbose_name='gwVoidMetadata'),
        ),
        migrations.AlterField(
            model_name='gwhydrogeovoid',
            name='gw_void_unit',
            field=models.ManyToManyField(blank=True, help_text='Relates hydrogeological units with a void hosted by the units.', null=True, to='gwml2.GWVoidUnit', verbose_name='gwVoidUnit'),
        ),
    ]
