# Generated by Django 2.2.12 on 2020-12-02 08:24

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0019_view_well_with_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellWithUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('feature_type', models.CharField(blank=True, max_length=512, null=True)),
                ('country', models.CharField(blank=True, max_length=512, null=True)),
                ('aquifer_name', models.CharField(blank=True, max_length=512, null=True)),
                ('aquifer_type', models.CharField(blank=True, max_length=512, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Location of the feature.', srid=4326, verbose_name='location')),
                ('uuid', models.CharField(blank=True, max_length=512, null=True)),
                ('detail', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'well_with_uuid',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='welllevelmeasurement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='welllevelmeasurement',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welllevelmeasurement',
            name='last_edited_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='welllevelmeasurement',
            name='last_edited_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellqualitymeasurement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='wellqualitymeasurement',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellqualitymeasurement',
            name='last_edited_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='wellqualitymeasurement',
            name='last_edited_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellyieldmeasurement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='wellyieldmeasurement',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellyieldmeasurement',
            name='last_edited_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='wellyieldmeasurement',
            name='last_edited_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
