# Generated by Django 2.2.12 on 2020-12-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0021_view_well_with_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='ggis_uid',
            field=models.CharField(blank=True, help_text='organisation name + Original ID', max_length=256, null=True),
        ),
    ]
