# Generated by Django 2.2.12 on 2020-07-06 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0022_gwwaterbudget_gw_budget_valid_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellPurposeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WellWaterUseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gwwell',
            name='gwWellReferenceElevation',
            field=models.ManyToManyField(blank=True, help_text='Reference elevation for all observations at the site, e.g. ground elevation, casing elevation.', null=True, to='gwml2.Elevation', verbose_name='gwWellReferenceElevation'),
        ),
        migrations.AddField(
            model_name='gwwell',
            name='gw_well_body',
            field=models.ForeignKey(blank=True, help_text='The fluid body occupying the well.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.GWFluidBody', verbose_name='gwWellBody'),
        ),
        migrations.AddField(
            model_name='gwwell',
            name='gw_well_unit',
            field=models.ManyToManyField(blank=True, help_text='The aquifers or confining beds intersecting the well.', null=True, to='gwml2.GWHydrogeoUnit', verbose_name='gwWellUnit'),
        ),
        migrations.AddField(
            model_name='gwwell',
            name='gw_well_yield',
            field=models.ForeignKey(blank=True, help_text='CEstimated or calculated yield from a well.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.GWYield', verbose_name='gwWellYield'),
        ),
        migrations.AddField(
            model_name='gwwell',
            name='gw_well_water_use',
            field=models.ManyToManyField(blank=True, help_text='Water use type of the well.', null=True, to='gwml2.WellWaterUseType', verbose_name='gwWellWaterUse'),
        ),
    ]
