# Generated by Django 2.2.12 on 2020-12-10 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0022_well_ggis_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterstrike',
            name='depth',
        ),
        migrations.AddField(
            model_name='waterstrike',
            name='reference_elevation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.TermReferenceElevationType'),
        ),
        migrations.AddField(
            model_name='waterstrike',
            name='water_depth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.Quantity'),
        ),
    ]
