# Generated by Django 2.2.12 on 2020-12-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0023_auto_20201210_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterstrike',
            old_name='water_depth',
            new_name='depth',
        ),
    ]
