# Generated by Django 2.2.12 on 2020-07-06 07:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0024_auto_20200706_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollarElevationTypeTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeadworkTypeTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='casingcomponent',
            name='casing_form',
            field=models.ForeignKey(blank=True, help_text='Form of material used in the casing. E.g.curbing, cribbing, corrugated, culvert, hose, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casing_form', to='gwml2.CasingFormTerm', verbose_name='casingForm'),
        ),
        migrations.CreateModel(
            name='BoreCollar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collar_location', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, help_text='The geographical location of the collar.', null=True, srid=4326, verbose_name='collarLocation')),
                ('bhole_headworks', models.ForeignKey(help_text='Relation between a borehole and its collar, which represents the top construction component of the borehole.', on_delete=django.db.models.deletion.CASCADE, to='gwml2.Borehole', verbose_name='bholeHeadworks')),
                ('collar_elevation_type', models.ForeignKey(blank=True, help_text='Type of reference elevation, defined as a feature,e.g. Top of Casing, Ground, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.CollarElevationTypeTerm', verbose_name='collarElevationType')),
                ('collar_headwork_type', models.ForeignKey(blank=True, help_text="Type of assembly bolted to the production casingto control the well, and to provide access andprotection (e.g. from flooding, vandalism).Example: raised tube, covers, manhole, 'GattickCover' flush, concrete ring, etc. (after Fretwell,et al., 2006).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.HeadworkTypeTerm', verbose_name='collarHeadworkType')),
            ],
        ),
    ]
