# Generated by Django 2.2.12 on 2020-12-10 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0024_auto_20201210_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='geology',
            name='reference_elevation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.TermReferenceElevationType'),
        ),
    ]
