# Generated by Django 2.2.12 on 2020-12-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0026_view_well_with_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruuid',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
