# Generated by Django 2.2.12 on 2020-12-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0028_view_well_with_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpingtest',
            name='storativity',
        ),
    ]
