# Generated by Django 2.2.12 on 2020-12-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0029_remove_pumpingtest_storativity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpingtest',
            name='storativity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pumping_test_storativity', to='gwml2.Quantity'),
        ),
    ]
