# Generated by Django 2.2.12 on 2020-12-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0030_pumpingtest_storativity'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='public',
            field=models.BooleanField(default=True, help_text='indicate that well can be viewed by non organisation user'),
        ),
    ]
