# Generated by Django 2.2.12 on 2020-12-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0034_auto_20201221_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrogeologyparameter',
            name='aquifer_thickness',
        ),
    ]
