# Generated by Django 2.2.12 on 2020-12-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0035_remove_hydrogeologyparameter_aquifer_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrogeologyparameter',
            name='aquifer_thickness',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
