# Generated by Django 2.2.12 on 2020-12-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0036_hydrogeologyparameter_aquifer_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='original_id',
            field=models.CharField(help_text='As recorded in the original database.', max_length=64),
        ),
    ]
