# Generated by Django 2.2.12 on 2020-12-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0036_hydrogeologyparameter_aquifer_thickness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WellWithUUID',
        ),
    ]
