# Generated by Django 2.2.12 on 2020-12-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0038_view_well_with_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadsession',
            options={'ordering': ('-start_at',), 'verbose_name': 'Download Session', 'verbose_name_plural': 'Download Sessions'},
        ),
        migrations.RenameField(
            model_name='downloadsession',
            old_name='uploaded_at',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='downloadsession',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DownloadSessionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwml2.DownloadSession')),
            ],
            options={
                'verbose_name': 'Download Session User',
                'verbose_name_plural': 'Download Sessions User',
                'db_table': 'download_session_user',
            },
        ),
    ]
