# Generated by Django 2.2.12 on 2020-12-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0039_auto_20201222_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='downloadable',
            field=models.BooleanField(default=True, help_text='indicate that well can be downloaded'),
        ),
    ]
