# Generated by Django 2.2.12 on 2020-12-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0040_well_downloadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='affiliate_organisations',
            field=models.ManyToManyField(blank=True, null=True, related_name='well_upload_affiliate_organisations', to='gwml2.Organisation'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='public',
            field=models.BooleanField(default=True, help_text='indicate that well can be viewed by non organisation user'),
        ),
    ]
