# Generated by Django 2.2.16 on 2021-01-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0042_uploadsession_downloadable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='well',
            name='number_of_measurements',
            field=models.IntegerField(default=0, help_text='Indicate how many measurement this well has'),
        ),
    ]
