# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0043_auto_20210106_0623'),
    ]

    # TODO:
    #  Always change gwmlw/models/views/well/WellWithUUID.py when this has changed

    sql = """
            CREATE VIEW well_with_uuid AS
            select w.id,
                   w.number_of_measurements                                                    as "number_of_measurements",
                   w.public                                                    as "public",
                   w.ggis_uid                                                  as "ggis_uid",
                   w.original_id                                               as "original_id",
                   w.name                                                      as "name",
                   type.name                                                   as "feature_type",
                   purpose.name                                                as "purpose",
                   status.name                                                 as "status",
                   org.name                                                    as "organisation",
                   c.name                                                      as "country",
                   drill.year_of_drilling                                      as "year_of_drilling",
                   hp.aquifer_name                                             as "aquifer_name",
                   aquifer.name                                                as "aquifer_type",
                   mg.manager                                                  as "manager",
                   w.location,
                   w.created_at                                                as "created_at",
                   created_by.username                                                as "created_by",
                   w.last_edited_at                                            as "last_edited_at",
                   last_edited_by.username                                                as "last_edited_by",
                   users.user_id                                               as "user_id",
                   uuid.uuid                                                   as "uuid",
                   concat('<a href="/groundwater/well/', w.id, '">Full Data Record</a>') as detail
            from well as w
                   LEFT JOIN organisation org on w.organisation_id = org.id
                   LEFT JOIN country c on w.country_id = c.id
                   LEFT JOIN term_feature_type type on w.feature_type_id = type.id
                   LEFT JOIN term_well_purpose purpose on w.purpose_id = purpose.id
                   LEFT JOIN term_well_status status on w.status_id = status.id
                   LEFT JOIN drilling drill on w.drilling_id = drill.id
                   LEFT JOIN hydrogeology_parameter hp on w.hydrogeology_parameter_id = hp.id
                   LEFT JOIN term_aquifer_type aquifer on hp.aquifer_type_id = aquifer.id
                   LEFT JOIN management mg on w.management_id = mg.id
                   LEFT JOIN user_uuid created_by on created_by.user_id = w.created_by
                   LEFT JOIN user_uuid last_edited_by on last_edited_by.user_id = w.last_edited_by
                   LEFT JOIN (
              select *
              from (
                     select w.id as well_id, org.name, unnest(org.admins || org.editors || org.viewers || 0) as user_id
                     from well as w
                            JOIN organisation org on org.id = w.organisation_id
                   ) well
              UNION
              (
                SELECT well_id, org.name, unnest(org.admins || org.editors || org.viewers) as user_id
                from well_affiliate_organisations as aff
                       JOIN organisation org on org.id = aff.organisation_id
              )
            ) AS users ON users.well_id = w.id
                   LEFT JOIN user_uuid uuid ON uuid.user_id = users.user_id
            ORDER BY user_id;
        """

    operations = [
        migrations.RunSQL('DROP VIEW IF EXISTS well_with_uuid;'),
        migrations.RunSQL(sql)
    ]
