# Generated by Django 2.2.16 on 2021-01-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0045_view_well_with_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConvertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(help_text='Use x as parameters for value from an unit.Example: m to cm, fill x*1000', max_length=512)),
                ('unit_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_convertion_unit_from', to='gwml2.Unit')),
                ('unit_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_convertion_unit_to', to='gwml2.Unit')),
            ],
            options={
                'db_table': 'unit_conversion',
                'unique_together': {('unit_from', 'unit_to')},
            },
        ),
    ]
