# Generated by Django 2.2.16 on 2021-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0047_auto_20210212_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='welllevelmeasurement',
            name='value_in_m',
            field=models.FloatField(default=0.0, editable=False, help_text='Converted value in meters'),
        ),
    ]
