# Generated by Django 2.2.16 on 2021-08-10 05:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0049_harvester_harvesterattribute_harvesterlog_harvesterwelldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='well',
            name='last_edited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last edited at'),
        ),
        migrations.AlterField(
            model_name='welllevelmeasurement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='welllevelmeasurement',
            name='last_edited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last edited at'),
        ),
        migrations.AlterField(
            model_name='wellqualitymeasurement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='wellqualitymeasurement',
            name='last_edited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last edited at'),
        ),
        migrations.AlterField(
            model_name='wellyieldmeasurement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='wellyieldmeasurement',
            name='last_edited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last edited at'),
        ),
    ]
