# Generated by Django 2.2.16 on 2021-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0050_auto_20210810_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='save_missing_well',
            field=models.BooleanField(default=False, help_text='Indicate that this harvester saves missing well.'),
        ),
    ]
