# Generated by Django 2.2.16 on 2022-01-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0051_harvester_save_missing_well'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WellWithUUID',
        ),
        migrations.AlterModelOptions(
            name='harvesterwelldata',
            options={'verbose_name_plural': 'Harvester well data'},
        ),
    ]
