# Generated by Django 2.2.16 on 2022-02-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0052_auto_20220111_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadsession',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gwml2.Well'),
        ),
    ]
