# Generated by Django 2.2.16 on 2022-06-01 03:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0053_downloadsession_well'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='viewers',
        ),
    ]
