# Generated by Django 2.2.16 on 2022-06-01 04:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0054_auto_20220601_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='affiliate_organisations',
        ),
        migrations.RemoveField(
            model_name='well',
            name='affiliate_organisations',
        ),
    ]
