# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0055_auto_20220601_0451'),
    ]

    # TODO:
    #  Always change gwmlw/models/views/well/Well.py when this has changed

    sql = """
            CREATE VIEW vw_well AS
            select w.id,
                   w.number_of_measurements                                                    as "number_of_measurements",
                   w.public                                                    as "public",
                   w.ggis_uid                                                  as "ggis_uid",
                   w.original_id                                               as "original_id",
                   w.name                                                      as "name",
                   type.name                                                   as "feature_type",
                   purpose.name                                                as "purpose",
                   status.name                                                 as "status",
                   org.name                                                    as "organisation",
                   c.name                                                      as "country",
                   drill.year_of_drilling                                      as "year_of_drilling",
                   hp.aquifer_name                                             as "aquifer_name",
                   aquifer.name                                                as "aquifer_type",
                   mg.manager                                                  as "manager",
                   w.location,
                   w.created_at                                                as "created_at",
                   created_by.username                                                as "created_by",
                   w.last_edited_at                                            as "last_edited_at",
                   last_edited_by.username                                                as "last_edited_by",
                   concat('<a href="/groundwater/record/', w.id, '">Full Data Record</a>') as detail
            from well as w
                   LEFT JOIN organisation org on w.organisation_id = org.id
                   LEFT JOIN country c on w.country_id = c.id
                   LEFT JOIN term_feature_type type on w.feature_type_id = type.id
                   LEFT JOIN term_well_purpose purpose on w.purpose_id = purpose.id
                   LEFT JOIN term_well_status status on w.status_id = status.id
                   LEFT JOIN drilling drill on w.drilling_id = drill.id
                   LEFT JOIN hydrogeology_parameter hp on w.hydrogeology_parameter_id = hp.id
                   LEFT JOIN term_aquifer_type aquifer on hp.aquifer_type_id = aquifer.id
                   LEFT JOIN management mg on w.management_id = mg.id
                   LEFT JOIN user_uuid created_by ON w.created_by = created_by.user_id
                   LEFT JOIN user_uuid last_edited_by ON w.last_edited_by = last_edited_by.user_id;
                   
            CREATE MATERIALIZED VIEW mv_well_ggmn AS select DISTINCT ON (id) id, organisation || '-' || original_id AS ggis_uid, original_id, name, feature_type,purpose, status,organisation, country, year_of_drilling, aquifer_name, aquifer_type,manager, detail, location, created_at, created_by, last_edited_at, last_edited_by, public from vw_well where "public" is True AND number_of_measurements > 0;
            CREATE MATERIALIZED VIEW mv_well AS select DISTINCT ON (id) id, organisation || '-' || original_id AS ggis_uid, original_id, name, feature_type,purpose, status,organisation, country, year_of_drilling, aquifer_name, aquifer_type,manager, detail, location, created_at, created_by, last_edited_at, last_edited_by, public from vw_well where "public" is True;
        """

    operations = [
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS mv_well_ggmn;'),
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS mv_well;'),
        migrations.RunSQL('DROP VIEW IF EXISTS vw_well;'),
        migrations.RunSQL(sql)
    ]
