# Generated by Django 2.2.16 on 2022-07-01 06:10

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0057_auto_20220629_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organisation_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('request_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Uploaded at')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=512, null=True, verbose_name='Surname')),
                ('organisation', models.CharField(max_length=512, verbose_name='Organization')),
                ('position', models.CharField(max_length=512)),
                ('organisation_types', models.CharField(max_length=512, verbose_name='Type of organization')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('countries', models.ManyToManyField(blank=True, null=True, to='gwml2.Country')),
            ],
        ),
    ]
