# Generated by Django 2.2.16 on 2022-09-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0059_view_well'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='downloadable',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='public',
        ),
        migrations.RemoveField(
            model_name='well',
            name='downloadable',
        ),
        migrations.RemoveField(
            model_name='well',
            name='public',
        ),
    ]
