# Generated by Django 2.2.28 on 2022-10-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0061_auto_20220901_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadrequest',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='downloadrequest',
            old_name='organisation_types',
            new_name='organization_types',
        ),
        migrations.RenameField(
            model_name='downloadrequest',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='downloadrequest',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='downloadrequest',
            name='position',
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.Country'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='download_country_data_request', to='gwml2.Country'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='data_type',
            field=models.CharField(choices=[('Well and Monitoring Data', 'Well and Monitoring Data'), ('GGMN', 'GGMN')], default='Well and Monitoring Data', max_length=512, verbose_name='Data type'),
        ),
    ]
