# Generated by Django 2.2.28 on 2022-10-26 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0062_auto_20221026_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='first_name',
            field=models.CharField(max_length=512, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Requested at'),
        ),
    ]
