# Generated by Django 2.2.28 on 2022-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0064_view_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='active',
            field=models.BooleanField(default=True, help_text='If not active, all well under it will be hidden'),
        ),
    ]
