# Generated by Django 2.2.28 on 2023-02-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0067_view_well'),
    ]
    operations = [
        migrations.AlterField(
            model_name='well',
            name='original_id',
            field=models.CharField(
                help_text='As recorded in the original database.',
                max_length=512, verbose_name='Original ID'),
        ),
    ]
