# Generated by Django 2.2.28 on 2023-02-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0067_view_well'),
    ]

    functions = """
            DROP TRIGGER IF EXISTS trigger_organisation ON organisation;
            DROP TRIGGER IF EXISTS trigger_user_uuid ON user_uuid;
            DROP TRIGGER IF EXISTS trigger_well ON well;
            DROP FUNCTION IF EXISTS update_mv();
    """
    operations = [
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS mv_well_ggmn;'),
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS mv_well;'),
        migrations.RunSQL('DROP VIEW IF EXISTS vw_well;'),
        migrations.RunSQL(functions),
        migrations.AlterField(
            model_name='well',
            name='original_id',
            field=models.CharField(
                help_text='As recorded in the original database.',
                max_length=512, verbose_name='Original ID'),
        ),
    ]
