# Generated by Django 3.2.16 on 2023-05-30 02:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0069_view_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
    ]
