# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0070_view_well'),
    ]

    views = """
            CREATE VIEW vw_istsos_sensor AS 
            SELECT well.id                              as id, 
                   ST_X(location)                       as longitude, 
                   ST_Y(location)                       as latitude, 
                   ground.value                         as elevation_value, 
                   unit.name                            as elevation_unit, 
                   well.original_id                     as original_id, 
                   well.ggis_uid                        as ggis_uid, 
                   well.name                            as name 
               from well 
                   LEFT JOIN quantity ground on ground.id = well.ground_surface_elevation_id 
                   LEFT JOIN unit on unit.id = ground.unit_id;
        """

    operations = [
        migrations.RunSQL(views),
    ]
