# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0070_organisation_groups'),
    ]

    # TODO:
    #  Always change gwmlw/models/views/well/Well.py when this has changed

    views = """
            CREATE VIEW vw_well AS
            select w.id,
                   w.number_of_measurements                                    as "number_of_measurements",
                   w.ggis_uid                                                  as "ggis_uid",
                   w.original_id                                               as "original_id",
                   w.name                                                      as "name",
                   type.name                                                   as "feature_type",
                   purpose.name                                                as "purpose",
                   status.name                                                 as "status",
                   org.name                                                    as "organisation",
                   '{0}' || org.groups                                         as "groups",
                   c.name                                                      as "country",
                   drill.year_of_drilling                                      as "year_of_drilling",
                   hp.aquifer_name                                             as "aquifer_name",
                   aquifer.name                                                as "aquifer_type",
                   mg.manager                                                  as "manager",
                   w.location,
                   w.created_at                                                as "created_at",
                   created_by.username                                                as "created_by",
                   w.last_edited_at                                            as "last_edited_at",
                   last_edited_by.username                                                as "last_edited_by",
                   concat('<a href="/groundwater/record/', w.id, '">Full Data Record</a>') as detail
            from well as w
                   LEFT JOIN organisation org on w.organisation_id = org.id
                   LEFT JOIN country c on w.country_id = c.id
                   LEFT JOIN term_feature_type type on w.feature_type_id = type.id
                   LEFT JOIN term_well_purpose purpose on w.purpose_id = purpose.id
                   LEFT JOIN term_well_status status on w.status_id = status.id
                   LEFT JOIN drilling drill on w.drilling_id = drill.id
                   LEFT JOIN hydrogeology_parameter hp on w.hydrogeology_parameter_id = hp.id
                   LEFT JOIN term_aquifer_type aquifer on hp.aquifer_type_id = aquifer.id
                   LEFT JOIN management mg on w.management_id = mg.id
                   LEFT JOIN user_uuid created_by ON w.created_by = created_by.user_id
                   LEFT JOIN user_uuid last_edited_by ON w.last_edited_by = last_edited_by.user_id
            WHERE org.active = True;
                   
            CREATE MATERIALIZED VIEW mv_well_ggmn AS select DISTINCT ON (id) id, organisation || '-' || original_id AS ggis_uid, original_id, name, feature_type,purpose, status,organisation, groups, country, year_of_drilling, aquifer_name, aquifer_type,manager, detail, location, created_at, created_by, last_edited_at, last_edited_by from vw_well where number_of_measurements > 0 and organisation is not null;
            CREATE MATERIALIZED VIEW mv_well AS select DISTINCT ON (id) id, organisation || '-' || original_id AS ggis_uid, original_id, name, feature_type,purpose, status,organisation, groups, country, year_of_drilling, aquifer_name, aquifer_type,manager, detail, location, created_at, created_by, last_edited_at, last_edited_by from vw_well;
        """

    functions = """
            DROP TRIGGER IF EXISTS trigger_organisation ON organisation;
            DROP TRIGGER IF EXISTS trigger_user_uuid ON user_uuid;
            DROP TRIGGER IF EXISTS trigger_well ON well;
            DROP FUNCTION IF EXISTS update_mv();
            
            CREATE FUNCTION update_mv() RETURNS trigger AS
            $update_mv$
            BEGIN
                refresh materialized view mv_well_ggmn;
                refresh materialized view mv_well;
                RETURN NEW;
            END;
            $update_mv$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trigger_well AFTER INSERT OR UPDATE ON well FOR EACH ROW EXECUTE PROCEDURE update_mv();
            CREATE TRIGGER trigger_organisation AFTER INSERT OR UPDATE ON organisation FOR EACH ROW EXECUTE PROCEDURE update_mv();
    """

    operations = [
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS mv_well_ggmn;'),
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS mv_well;'),
        migrations.RunSQL('DROP VIEW IF EXISTS vw_well;'),
        migrations.RunSQL(views),
        migrations.RunSQL(functions),
    ]
