# Generated by Django 3.2.16 on 2023-06-08 03:22

import django
from django.db import migrations, models

from gwml2.models.term_measurement_parameter import TermMeasurementParameter
from gwml2.models.well import Well


def assign_first_last(query, well: Well):
    first = query.order_by('time').first()
    if first and (
            not well.first_time_measurement or
            first.time < well.first_time_measurement
    ):
        well.first_time_measurement = first.time

    last = query.order_by('time').last()
    if last and (
            not well.first_time_measurement or
            last.time > well.first_time_measurement
    ):
        well.last_time_measurement = last.time
    return well


def run(apps, schema_editor):
    for well in Well.objects.all():
        well = assign_first_last(well.welllevelmeasurement_set.all(), well)
        well = assign_first_last(well.wellyieldmeasurement_set.all(), well)
        well = assign_first_last(well.wellqualitymeasurement_set.all(), well)
        well.save()

    for param in TermMeasurementParameter.objects.all():
        param.default_unit = param.units.first()
        param.save()


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0070_view_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='first_time_measurement',
            field=models.DateTimeField(blank=True, null=True,
                                       verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='well',
            name='last_time_measurement',
            field=models.DateTimeField(blank=True, null=True,
                                       verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='termmeasurementparameter',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='term_measurement_parameter_default_unit',
                                    to='gwml2.unit'),
        ),
        migrations.AddField(
            model_name='welllevelmeasurement',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='gwml2.unit'),
        ),
        migrations.AddField(
            model_name='welllevelmeasurement',
            name='default_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellqualitymeasurement',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='gwml2.unit'),
        ),
        migrations.AddField(
            model_name='wellqualitymeasurement',
            name='default_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellyieldmeasurement',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='gwml2.unit'),
        ),
        migrations.AddField(
            model_name='wellyieldmeasurement',
            name='default_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
