# Generated by Django 3.2.16 on 2023-06-08 03:22

import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0070_view_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='first_time_measurement',
            field=models.DateTimeField(blank=True, null=True,
                                       verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='well',
            name='last_time_measurement',
            field=models.DateTimeField(blank=True, null=True,
                                       verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='termmeasurementparameter',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='term_measurement_parameter_default_unit',
                                    to='gwml2.unit'),
        ),
        migrations.AddField(
            model_name='welllevelmeasurement',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='gwml2.unit'),
        ),
        migrations.AddField(
            model_name='welllevelmeasurement',
            name='default_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellqualitymeasurement',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='gwml2.unit'),
        ),
        migrations.AddField(
            model_name='wellqualitymeasurement',
            name='default_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellyieldmeasurement',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='gwml2.unit'),
        ),
        migrations.AddField(
            model_name='wellyieldmeasurement',
            name='default_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
