# Generated by Django 3.2.16 on 2023-06-08 03:22

from django.db import migrations
from django.db.models.signals import post_save, pre_save

from gwml2.models.well import (
    Well, WellYieldMeasurement, WellQualityMeasurement, WellLevelMeasurement
)
from gwml2.signals.well import (
    post_save_measurement_for_cache,
    pre_save_measurement, post_save_measurement
)
from gwml2.utilities import Signal, temp_disconnect_signals


def update_measurement_default_db(query):
    for measurement in query:
        measurement.set_default_value()
        measurement.save()


def run(apps, schema_editor):
    for well in Well.objects.order_by('-number_of_measurements')[:1]:
        with temp_disconnect_signals(
                [
                    Signal(pre_save, pre_save_measurement,
                           WellLevelMeasurement),
                    Signal(pre_save, pre_save_measurement,
                           WellYieldMeasurement),
                    Signal(pre_save, pre_save_measurement,
                           WellQualityMeasurement),
                    Signal(post_save, post_save_measurement,
                           WellLevelMeasurement),
                    Signal(post_save, post_save_measurement,
                           WellYieldMeasurement),
                    Signal(post_save, post_save_measurement,
                           WellQualityMeasurement),
                    Signal(post_save, post_save_measurement_for_cache,
                           WellLevelMeasurement),
                    Signal(post_save, post_save_measurement_for_cache,
                           WellYieldMeasurement),
                    Signal(post_save, post_save_measurement_for_cache,
                           WellQualityMeasurement),
                ]
        ):
            update_measurement_default_db(well.welllevelmeasurement_set.all())
            update_measurement_default_db(well.wellyieldmeasurement_set.all())
            update_measurement_default_db(
                well.wellqualitymeasurement_set.all()
            )


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0071_auto_20230608_0322'),
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
