# Generated by Django 3.2.20 on 2023-11-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0072_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
