# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0073_view_well'),
    ]

    views = """
            CREATE SCHEMA IF NOT EXISTS istsos;
            
            -- PROCEDURES --
            CREATE VIEW istsos.procedures AS 
            SELECT w.id                                 as id_prc,
                   ''                                   as assignedid_prc,
                   w.original_id                        as name_prc,
                   w.description                        as desc_prc,
                   w.first_time_measurement             as stime_prc,
                   w.last_time_measurement              as etime_prc,
                   null                                 as time_res_prc,
                   null                                 as time_acq_prc,
                   p.id                                 as id_oty_fk,
                   w.id                                 as id_foi_fk,
                   ''                                   as mqtt_prc
            from vw_well as w LEFT JOIN term_well_purpose as p ON p.id=w.purpose_id;
            
            -- OBS_TYPE --
            CREATE VIEW istsos.obs_type AS 
            SELECT id               as id_oty,
                   name             as name_oty,
                   description      as desc_oty
            from term_well_purpose;
            
            -- OBSERVED_PROPERTIES --
            CREATE VIEW istsos.observed_properties AS 
            SELECT p.id                                                             as id_opr,
                   p.name                                                           as name_opr,
                   concat('urn:ogc:def:parameter:x-igrac:1.0:',g.name,':',p.name)   as def_opr,
                   p.description                                                    as desc_opr,
                   u.id                                                             as unit_id,
                   u.name                                                           as unit_name,
                   u.description                                                    as unit_description,
                   ''                                                               as constr_opr
            from term_measurement_parameter as p
                LEFT JOIN term_measurement_parameter_group_parameters as r ON r.termmeasurementparameter_id=p.id
                LEFT JOIN term_measurement_parameter_group as g ON r.termmeasurementparametergroup_id=g.id
                LEFT JOIN unit as u ON u.id=p.default_unit_id;
            
            -- UOMS --
            CREATE VIEW istsos.uoms AS 
            SELECT unit_name            as name_uom,
                   unit_description     as desc_uom,
                   unit_id              as id_uom
            from istsos.observed_properties WHERE unit_id IS NOT NULL GROUP BY unit_id, unit_name, unit_description;
            
            -- PROC_OBS --
            CREATE VIEW istsos.proc_obs AS 
            SELECT concat(opr.id_opr,opr.unit_id,proc.id_prc)   as id_pro,
                   opr.id_opr                                   as id_opr_fk,
                   opr.unit_id                                  as id_uom_fk,
                   proc.id_prc                                  as id_prc_fk,
                   ''                                           as constr_pro
            from istsos.observed_properties as opr CROSS JOIN istsos.procedures as proc;
            
            -- TEMPORARY --
            CREATE VIEW istsos.vw_istsos_sensor AS
            SELECT well.id                              as id,
                   ST_X(location)                       as longitude,
                   ST_Y(location)                       as latitude,
                   ground.value                         as elevation_value,
                   unit.name                            as elevation_unit,
                   well.original_id                     as original_id,
                   well.ggis_uid                        as ggis_uid,
                   well.name                            as name
           from well
                   LEFT JOIN quantity ground on ground.id = well.ground_surface_elevation_id
                   LEFT JOIN unit on unit.id = ground.unit_id;
        """

    default = """
        DROP VIEW IF EXISTS istsos.obs_type;
        DROP VIEW IF EXISTS istsos.uoms;
        DROP VIEW IF EXISTS istsos.proc_obs;
        DROP VIEW IF EXISTS istsos.observed_properties;
        DROP VIEW IF EXISTS istsos.procedures;
        DROP VIEW IF EXISTS istsos.vw_istsos_sensor;
        DROP SCHEMA IF EXISTS istsos;
    """

    operations = [
        migrations.RunSQL(default, default),
        migrations.RunSQL(views, default),
    ]
