# Generated by Django 3.2.20 on 2023-12-15 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0074_welldeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='step',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='task_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadsessionrowstatus',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.well'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.TextField(blank=True, help_text=('What is the status of progress. Mostly it will split by added, error and skipped ',), null=True),
        ),
    ]
