# Generated by Django 3.2.20 on 2023-12-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0074_welldeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='task_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.TextField(blank=True, help_text=('What is the status of progress. Mostly it will split by added, error and skipped ',), null=True),
        ),
    ]
