# Generated by Django 3.2.20 on 2023-12-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0075_alter_uploadsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='task_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
