# Generated by Django 3.2.20 on 2023-12-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0075_auto_20231215_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='number_of_measurements_level',
            field=models.IntegerField(default=0, help_text='Indicate how many level measurement this well has.'),
        ),
        migrations.AddField(
            model_name='well',
            name='number_of_measurements_quality',
            field=models.IntegerField(default=0, help_text='Indicate how many quality measurement this well has.'),
        ),
        migrations.AddField(
            model_name='well',
            name='number_of_measurements_yield',
            field=models.IntegerField(default=0, help_text='Indicate how many yield measurement this well has.'),
        ),
    ]
