# Generated by Django 3.2.20 on 2024-01-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0077_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='category',
            field=models.CharField(blank=True, choices=[('well_upload', 'well_upload'), ('well_monitoring_upload', 'well_monitoring_upload'), ('well_drilling_and_construction', 'well_drilling_and_construction')], default='', max_length=50),
        ),
    ]
