# Generated by Django 3.2.20 on 2024-02-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0078_alter_uploadsession_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesterattribute',
            name='value',
            field=models.TextField(default=True, help_text='The value of attribute', null=True),
        ),
    ]
