# Generated by Django 3.2.20 on 2024-02-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0079_alter_harvesterattribute_value'),
        ('gwml2', '0079_downloadrequest_organisations'),
    ]

    operations = [
    ]
