# Generated by Django 3.2.20 on 2024-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0080_downloadrequest_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='ggis_uid',
            field=models.CharField(blank=True, help_text='organisation name + Original ID', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Name'),
        )
    ]
