# Generated by Django 3.2.20 on 2024-03-22 14:35

from django.db import migrations, models
from gwml2.migrations.sql.utils import load_sql


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0080_downloadrequest_organisations'),
    ]

    gwml_default = load_sql('gwml', 'default.sql')
    gwml_views = load_sql('gwml', 'views.sql')
    gwml_functions = load_sql('gwml', 'functions.sql')

    istsos_default = load_sql('istsos', 'default.sql')
    istsos_views = load_sql('istsos', 'views.sql')

    operations = [
        migrations.RunSQL(istsos_default, istsos_default),
        migrations.RunSQL(gwml_default, gwml_default),
        migrations.AlterField(
            model_name='well',
            name='ggis_uid',
            field=models.CharField(blank=True, help_text='organisation name + Original ID', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Name'),
        ),
        migrations.RunSQL(gwml_views, gwml_default),
        migrations.RunSQL(gwml_functions, gwml_default),
        migrations.RunSQL(istsos_views, istsos_default),
    ]
