# Generated by Django 3.2.20 on 2024-04-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0082_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.ForeignKey(blank=True, help_text="Identify the country of the organisation. It is being used to assign well's country under this organisation. If this is empty, all well under this organisation will be assigned based on geometry of country.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwml2.country'),
        ),
    ]
