# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations

from gwml2.migrations.sql.utils import load_sql


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0083_organisation_country'),
    ]

    operations = [
    ]
