# Generated by Django 3.2.20 on 2024-07-25 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0086_alter_downloadrequest_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesterwelldata',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwml2.well'),
        ),
    ]
