# Generated by Django 3.2.20 on 2024-10-04 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0087_alter_harvesterwelldata_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='glo_90m_elevation',
            field=models.OneToOneField(blank=True, help_text='DEM elevation based on the GLO_90m dataset above sea level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glo_90m_elevation', to='gwml2.quantity', verbose_name='DEM elevation based on the GLO_90m dataset above sea level'),
        ),
    ]
