# Generated by Django 3.2.20 on 2024-11-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0088_well_glo_90m_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='is_adding',
            field=models.BooleanField(default=True, help_text='Does the upload add new data.'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='is_updating',
            field=models.BooleanField(default=False, help_text='Does the update existing data.'),
        ),
    ]
