# Generated by Django 3.2.20 on 2025-01-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0089_auto_20241112_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='first_time_measurement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First time measurement'),
        ),
        migrations.AlterField(
            model_name='well',
            name='last_time_measurement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last time measurement'),
        ),
    ]
