# Generated by Django 2.2.12 on 2020-07-03 09:03

from gwml2.migrations.sql.view_well_migrations import ViewWellMigration


class Migration(ViewWellMigration):
    dependencies = [
        ('gwml2', '0091_auto_20250124_0553'),
    ]
