# Generated by Django 3.2.20 on 2025-01-24 03:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0091_view_well'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializedViewWell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ggis_uid', models.CharField(help_text='Organisation + id.', max_length=512)),
                ('original_id', models.CharField(help_text='As recorded in the original database.', max_length=512)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('feature_type', models.CharField(blank=True, max_length=512, null=True)),
                ('purpose', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(blank=True, max_length=512, null=True)),
                ('organisation', models.CharField(blank=True, max_length=512, null=True)),
                ('organisation_id', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=512, null=True)),
                ('year_of_drilling', models.PositiveIntegerField(blank=True, null=True)),
                ('aquifer_name', models.CharField(blank=True, max_length=512, null=True)),
                ('aquifer_type', models.CharField(blank=True, max_length=512, null=True)),
                ('manager', models.CharField(blank=True, max_length=512, null=True)),
                ('detail', models.CharField(blank=True, max_length=512, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('last_edited_by', models.IntegerField(blank=True, null=True)),
                ('number_of_measurements_level', models.IntegerField()),
                ('number_of_measurements_quality', models.IntegerField()),
                ('number_of_measurements_yield', models.IntegerField()),
                ('first_time_measurement', models.DateTimeField(blank=True, null=True)),
                ('last_time_measurement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mv_well',
                'ordering': ['original_id'],
                'managed': False,
            },
        ),
    ]
