# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0091_auto_20250124_0657'),
    ]

    operations = [
    ]
