# Generated by Django 3.2.20 on 2025-01-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0092_view_well'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='harvester_class',
            field=models.CharField(help_text='The type of harvester that will be used.Use class with full package.', max_length=100),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='name',
            field=models.CharField(help_text='Name of harvester that.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='harvester',
            unique_together={('harvester_class', 'name')},
        ),
    ]
