# Generated by Django 3.2.20 on 2025-02-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0093_auto_20250124_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='measurement_cache_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time when measurement cache generated'),
        ),
    ]
