# Generated by Django 3.2.20 on 2025-02-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0094_well_measurement_cache_generated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_amsl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_preference_parameter_amsl', to='gwml2.termmeasurementparameter')),
                ('parameter_from_ground_surface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_preference_parameter_from_ground_surface', to='gwml2.termmeasurementparameter')),
                ('parameter_from_top_well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_preference_parameter_from_top_well', to='gwml2.termmeasurementparameter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
