# Generated by Django 3.2.20 on 2025-03-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0095_sitepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='welldeletion',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
