# Generated by Django 3.2.20 on 2025-03-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0096_welldeletion_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='data_cache_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time when data cache generated'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='data_cache_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time when data cache generated'),
        ),
        migrations.AddField(
            model_name='well',
            name='data_cache_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time when data cache generated'),
        ),
    ]
