# Generated by Django 3.2.20 on 2025-04-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwml2', '0097_auto_20250321_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreference',
            name='batch_upload_auto_resume',
            field=models.BooleanField(default=False, help_text='Auto resume flag for batch upload.'),
        ),
    ]
