# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations


# TODO:
#  We need to update the view migrations as the server can't handle it
class Migration(migrations.Migration):
    dependencies = [
        ('gwml2', '0099_auto_20250417_0401'),
    ]

    operations = [
    ]
