# Generated by Django 2.2.12 on 2020-07-03 09:03

from gwml2.migrations.sql.view_well_migrations import ViewWellMigration


# TODO:
#  We need to update the view migrations as the server can't handle it
class Migration(ViewWellMigration):
    dependencies = [
        ('gwml2', '0100_view_well'),
    ]
