# Generated by Django 4.2.17 on 2025-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0101_view_well"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadrequest",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("GGMN", "GGMN"),
                    ("Well and Monitoring Data", "Groundwater Observations Repository"),
                ],
                default="GGMN",
                max_length=512,
                verbose_name="Data type",
            ),
        ),
    ]
