# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations

from gwml2.migrations.sql.utils import load_sql


class Migration(migrations.Migration):
    dependencies = [
        ("gwml2", "0102_alter_downloadrequest_data_type"),
    ]

    gwml_functions = load_sql('gwml', 'functions.sql')
    default = """
        DROP TRIGGER IF EXISTS trigger_country ON country;
        DROP TRIGGER IF EXISTS trigger_organisation ON organisation;
        DROP TRIGGER IF EXISTS trigger_well ON well;
        DROP FUNCTION IF EXISTS update_mv();
        DROP MATERIALIZED VIEW IF EXISTS mv_well_ggmn;
    """

    operations = [
        migrations.RunSQL(default, default),
        migrations.RunSQL(gwml_functions, default),
    ]
