# Generated by Django 4.2.17 on 2025-06-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0103_remove_mv_well_ggmn"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsession",
            name="retry",
            field=models.IntegerField(default=0),
        ),
    ]
