# Generated by Django 4.2.17 on 2025-06-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0104_uploadsession_retry"),
    ]

    operations = [
        migrations.AddField(
            model_name="well",
            name="data_cache_information",
            field=models.JSONField(
                blank=True,
                help_text="Information about the data cache, like the time of file is being generated.",
                null=True,
            ),
        ),
    ]
