# Generated by Django 4.2.17 on 2025-06-30 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0104_uploadsession_retry"),
    ]

    operations = [
        migrations.CreateModel(
            name="HarvesterParameterMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="The key on the api", max_length=512),
                ),
                (
                    "harvester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gwml2.harvester",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gwml2.termmeasurementparameter",
                    ),
                ),
            ],
            options={
                "db_table": "harvester_parameter_map",
                "unique_together": {("harvester", "parameter")},
            },
        ),
    ]
