# Generated by Django 4.2.17 on 2025-07-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0105_harvesterparametermap"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvesterparametermap",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gwml2.unit",
            ),
        ),
    ]
