# Generated by Django 4.2.17 on 2025-07-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0106_harvesterparametermap_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="harvesterparametermap",
            options={"ordering": ("key",)},
        ),
        migrations.AlterUniqueTogether(
            name="harvesterparametermap",
            unique_together={("harvester", "key")},
        ),
    ]
