# Generated by Django 4.2.17 on 2025-07-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0108_harvester_task_id_sitepreference_running_harvesters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="constraints_other",
            field=models.TextField(
                blank=True,
                help_text="other restrictions and legal prerequisites for accessing and using the resource or metadata",
                null=True,
                verbose_name="restrictions other",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="data_date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="data_date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="data_is_from_api",
            field=models.BooleanField(
                default=False,
                help_text="If true, this organisation data is created from API.For telling the timerange is Updated automatically (via API).",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="data_is_groundwater_level",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="data_is_groundwater_quality",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="license",
            field=models.IntegerField(
                blank=True,
                help_text="license of the dataset. this is ID of license in geonode.",
                null=True,
                verbose_name="License",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="restriction_code_type",
            field=models.IntegerField(
                blank=True,
                help_text="limitation(s) placed upon the access or use of the data. this is ID of restriction code in geonode.",
                null=True,
                verbose_name="Restrictions",
            ),
        ),
        migrations.CreateModel(
            name="OrganisationLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "url",
                    models.URLField(
                        help_text="URL of the organisation link", max_length=512
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="gwml2.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "organisation_link",
            },
        ),
    ]
