# Generated by Django 4.2.17 on 2025-07-10 06:24

from django.db import migrations, models


def create_ggmn_group(apps, schema_editor):
    OrganisationGroup = apps.get_model('gwml2', 'OrganisationGroup')
    OrganisationGroup.objects.create(
        name='The Global Groundwater Monitoring Network (GGMN)'
    )


class Migration(migrations.Migration):
    dependencies = [
        ("gwml2", "0109_organisation_constraints_other_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "download_readme_text",
                    models.TextField(
                        blank=True,
                        help_text="Readme text to be included in the download zip file.",
                        null=True,
                    ),
                ),
                (
                    "organisations",
                    models.ManyToManyField(
                        blank=True, related_name="groups",
                        to="gwml2.organisation"
                    ),
                ),
            ],
            options={
                "db_table": "organisation_group",
            },
        ),
        migrations.RunPython(create_ggmn_group, migrations.RunPython.noop),
    ]
