# Generated by Django 4.2.17 on 2025-08-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0110_organisationgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="well",
            name="estimated_flow",
            field=models.CharField(
                blank=True,
                help_text="Estimated flow rate for springs.",
                max_length=512,
                null=True,
                verbose_name="Estimated flow",
            ),
        ),
    ]
