# Generated by Django 4.2.17 on 2025-08-11 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0111_well_estimated_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellQualityControl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groundwater_level_time_gap",
                    models.JSONField(
                        blank=True,
                        help_text="Filled with some of bad quality info by time gap for Groundwater level measurement.",
                        null=True,
                    ),
                ),
                (
                    "groundwater_level_time_gap_generated_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "groundwater_level_value_gap",
                    models.JSONField(
                        blank=True,
                        help_text="Filled with some of bad quality info by level gap for Groundwater level measurement.",
                        null=True,
                    ),
                ),
                (
                    "groundwater_level_value_gap_generated_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "groundwater_level_strange_value",
                    models.JSONField(
                        blank=True,
                        help_text="Filled with some of bad quality info by strange value for Groundwater level measurement.",
                        null=True,
                    ),
                ),
                (
                    "groundwater_level_strange_value_generated_time",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "well_quality_control",
            },
        ),
        migrations.AddField(
            model_name="sitepreference",
            name="groundwater_level_quality_control_days_gap",
            field=models.IntegerField(
                default=1095,
                help_text="Quality control days gap for groundwater level measurement. The gap is more than the value, it is basically a bad quality.",
            ),
        ),
        migrations.AddField(
            model_name="sitepreference",
            name="groundwater_level_quality_control_level_gap",
            field=models.IntegerField(
                default=50,
                help_text="Quality control level gap for groundwater level measurement. The gap is more than the value, it is basically a bad quality.",
            ),
        ),
        migrations.AddField(
            model_name="sitepreference",
            name="groundwater_level_strange_value_filter",
            field=models.TextField(
                default="value_in_m IN (0, -9999)",
                help_text="This is for query filter for the strange value.Use postgres filter syntax. ",
            ),
        ),
        migrations.AddIndex(
            model_name="welllevelmeasurement",
            index=models.Index(
                fields=["well", "time"], name="well_level__well_id_1108af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="welllevelmeasurement",
            index=models.Index(
                fields=["well", "parameter", "time"],
                name="well_level__well_id_5c4700_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellqualitymeasurement",
            index=models.Index(
                fields=["well", "parameter", "time"],
                name="well_qualit_well_id_209aae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellyieldmeasurement",
            index=models.Index(
                fields=["well", "parameter", "time"],
                name="well_yield__well_id_f1e2fb_idx",
            ),
        ),
        migrations.AddField(
            model_name="wellqualitycontrol",
            name="well",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="gwml2.well"
            ),
        ),
    ]
