# Generated by Django 4.2.17 on 2025-08-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0111_well_estimated_flow"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="welllevelmeasurement",
            index=models.Index(
                fields=["well", "time"], name="well_level__well_id_1108af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="welllevelmeasurement",
            index=models.Index(
                fields=["well", "parameter", "time"],
                name="well_level__well_id_5c4700_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellqualitymeasurement",
            index=models.Index(
                fields=["well", "parameter", "time"],
                name="well_qualit_well_id_209aae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellyieldmeasurement",
            index=models.Index(
                fields=["well", "parameter", "time"],
                name="well_yield__well_id_f1e2fb_idx",
            ),
        ),
    ]
