# Generated by Django 4.2.17 on 2025-08-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0111_well_estimated_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitepreference",
            name="quality_control_days_gap",
            field=models.IntegerField(
                default=1095,
                help_text="Quality control days gap. The gap is more than the value, it is basically a bad quality.",
            ),
        ),
        migrations.AddField(
            model_name="sitepreference",
            name="quality_control_level_gap",
            field=models.IntegerField(
                default=50,
                help_text="Quality control level gap. Specifically for well measurement.The gap is more than the value, it is basically a bad quality.",
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="bad_quality_level_gap",
            field=models.TextField(
                blank=True,
                help_text="Filled with some of bad quality info by level gap.Specifically for level measurement.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="bad_quality_level_gap_generated_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="well",
            name="bad_quality_time_gap",
            field=models.TextField(
                blank=True,
                help_text="Filled with some of bad quality info by time gap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="bad_quality_time_gap_generated_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="welllevelmeasurement",
            index=models.Index(
                fields=["well", "time"], name="well_level__well_id_1108af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="welllevelmeasurement",
            index=models.Index(
                fields=["well", "parameter", "time"],
                name="well_level__well_id_5c4700_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellqualitymeasurement",
            index=models.Index(
                fields=["well", "parameter", "time"],
                name="well_qualit_well_id_209aae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellyieldmeasurement",
            index=models.Index(
                fields=["well", "parameter", "time"],
                name="well_yield__well_id_f1e2fb_idx",
            ),
        ),
    ]
