# Generated by Django 4.2.17 on 2025-08-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0112_wellqualitycontrol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellCacheIndicator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurement_cache_generated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Time when measurement cache generated",
                    ),
                ),
                (
                    "data_cache_generated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Time when data cache generated",
                    ),
                ),
                (
                    "metadata_generated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Time when metadata generated",
                    ),
                ),
                (
                    "well",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="gwml2.well"
                    ),
                ),
            ],
        ),
    ]
