# Generated by Django 4.2.17 on 2025-08-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0114_view_well"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termaquifertype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="termconfinement",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="termconstructionstructuretype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="termdrillingmethod",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="termfeaturetype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="termgroundwateruse",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="termmeasurementparameter",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="termmeasurementparametergroup",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="termreferenceelevationtype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="termwellpurpose",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="termwellstatus",
            options={
                "ordering": ["name"],
                "verbose_name": "Term well status",
                "verbose_name_plural": "Term well status",
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="unitgroup",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="termaquifertype",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termconfinement",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termconstructionstructuretype",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termdrillingmethod",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termfeaturetype",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termgroundwateruse",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termmeasurementparameter",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termmeasurementparametergroup",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termreferenceelevationtype",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termwellpurpose",
            name="order",
        ),
        migrations.RemoveField(
            model_name="termwellstatus",
            name="order",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="order",
        ),
        migrations.RemoveField(
            model_name="unitgroup",
            name="order",
        ),
    ]
