# Generated by Django 4.2.17 on 2025-08-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0115_alter_termaquifertype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="well",
            name="constraints_other",
        ),
        migrations.RemoveField(
            model_name="well",
            name="license",
        ),
        migrations.RemoveField(
            model_name="well",
            name="restriction_code_type",
        ),
    ]
