# Generated by Django 4.2.17 on 2025-09-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0116_remove_well_constraints_other_remove_well_license_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellcacheindicator",
            name="data_cache_information",
            field=models.JSONField(
                blank=True,
                help_text="Information about the data cache, like the time of file is being generated.",
                null=True,
            ),
        ),
    ]
