# Generated by Django 4.2.17 on 2025-09-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0117_wellcacheindicator_data_cache_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="data_cache_information",
            field=models.JSONField(
                blank=True,
                help_text="Information about the data cache, like the time of file is being generated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="data_cache_information",
            field=models.JSONField(
                blank=True,
                help_text="Information about the data cache, like the time of file is being generated.",
                null=True,
            ),
        ),
    ]
