# Generated by Django 4.2.17 on 2026-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0118_country_data_cache_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadrequest",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="downloadrequest",
            name="organization",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Organization"
            ),
        ),
        migrations.AlterField(
            model_name="downloadrequest",
            name="organization_types",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Type of organization",
            ),
        ),
    ]
