# Generated by Django 4.2.17 on 2026-01-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0119_alter_downloadrequest_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadrequest",
            name="organization",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Organization"
            ),
        ),
        migrations.AlterField(
            model_name="downloadrequest",
            name="organization_types",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Type of organization",
            ),
        ),
    ]
