# Generated by Django 4.2.17 on 2026-05-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0119_alter_downloadrequest_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="measurement_stats",
            field=models.JSONField(
                blank=True,
                help_text="Counts of total/midnight measurements per type.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="measurement_stats_generated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Time when measurement stats were generated",
            ),
        ),
    ]
