# Generated by Django 4.2.17 on 2026-05-22 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0120_organisation_measurement_stats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="welllevelmeasurement",
            name="depth_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="gwml2.unit",
            ),
        ),
        migrations.AddField(
            model_name="welllevelmeasurement",
            name="depth_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wellqualitymeasurement",
            name="depth_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="gwml2.unit",
            ),
        ),
        migrations.AddField(
            model_name="wellqualitymeasurement",
            name="depth_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wellyieldmeasurement",
            name="depth_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="gwml2.unit",
            ),
        ),
        migrations.AddField(
            model_name="wellyieldmeasurement",
            name="depth_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
