# Generated by Django 4.2.17 on 2026-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0121_welllevelmeasurement_depth_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="data_is_groundwater_level",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="data_is_groundwater_quality",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="measurement_stats",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="measurement_stats_generated_at",
        ),
        migrations.AddField(
            model_name="organisation",
            name="data_stats",
            field=models.JSONField(
                blank=True,
                help_text="Cached statistics for this organisation: measurement counts (total, per type, midnight) and well counts (total, with level/quality data, springs).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="data_stats_generated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Time when data stats were generated",
            ),
        ),
    ]
