# Generated by Django 4.2.17 on 2026-06-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0123_well_glo_90m_elevation_empty_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="well",
            name="data_cache_generated_at",
        ),
        migrations.RemoveField(
            model_name="well",
            name="measurement_cache_generated_at",
        ),
        migrations.RemoveField(
            model_name="wellcacheindicator",
            name="measurement_cache_generated_at",
        ),
    ]
