# Generated by Django 4.2.17 on 2026-06-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0124_remove_well_data_cache_generated_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HarvesterWellData",
        ),
    ]
