# Generated by Django 4.2.17 on 2026-06-24 07:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0125_delete_harvesterwelldata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="data_cache_information",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="data_cache_information",
        ),
        migrations.AddField(
            model_name="downloadrequest",
            name="is_error",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="downloadrequest",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="downloadrequest",
            name="wells_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="downloadrequest",
            name="countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="download_country_data_request",
                to="gwml2.country",
            ),
        ),
        migrations.AlterField(
            model_name="downloadrequest",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                related_name="download_organisation_data_request",
                to="gwml2.organisation",
            ),
        ),
    ]
