# Generated by Django 4.2.17 on 2026-06-30 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0126_remove_country_data_cache_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadrequest",
            name="request_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Requested at",
            ),
        ),
    ]
