# Generated by Django 4.2.17 on 2026-06-30 09:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0127_alter_downloadrequest_request_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvesterlog",
            name="well_progress",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(),
                blank=True,
                default=list,
                help_text='Per-well progress. Each entry: {"id": original_id, "status": "saved"|"no_change"|"error", "note": "..."}',
                size=None,
            ),
        ),
    ]
