# Generated by Django 4.2.17 on 2026-07-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0129_view_well"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="welllevelmeasurement",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="welllevelmeasurement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="welllevelmeasurement",
            name="last_edited_at",
        ),
        migrations.RemoveField(
            model_name="welllevelmeasurement",
            name="last_edited_by",
        ),
        migrations.RemoveField(
            model_name="wellqualitymeasurement",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wellqualitymeasurement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="wellqualitymeasurement",
            name="last_edited_at",
        ),
        migrations.RemoveField(
            model_name="wellqualitymeasurement",
            name="last_edited_by",
        ),
        migrations.RemoveField(
            model_name="wellyieldmeasurement",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wellyieldmeasurement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="wellyieldmeasurement",
            name="last_edited_at",
        ),
        migrations.RemoveField(
            model_name="wellyieldmeasurement",
            name="last_edited_by",
        ),
    ]
