# Generated by Django 4.2.17 on 2026-07-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0129_view_well"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="data_stats_generated_at",
        ),
        migrations.AddField(
            model_name="organisation",
            name="metadata_cache_generated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Time when metadata cache were generated",
            ),
        ),
    ]
