# Generated by Django 4.2.17 on 2026-07-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0130_remove_welllevelmeasurement_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="data_stats_generated_at",
        ),
        migrations.AddField(
            model_name="country",
            name="metadata_cache",
            field=models.JSONField(
                blank=True,
                help_text="Cached statistics for this country (all wells).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="metadata_cache_generated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Time when metadata cache were generated",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="metadata_cache_ggmn",
            field=models.JSONField(
                blank=True,
                help_text="Cached statistics for this country for GGMN.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="metadata_cache_generated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Time when metadata cache were generated",
            ),
        ),
    ]
