# Generated by Django 4.2.17 on 2026-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0131_remove_organisation_data_stats_generated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadrequest",
            name="profession",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Profession"
            ),
        ),
    ]
