# Generated by Django 4.2.17 on 2026-07-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0132_downloadrequest_profession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="harvesterlog",
            name="well_progress",
        ),
    ]
