# Generated by Django 4.2.17 on 2026-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0133_remove_harvesterlog_well_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="well",
            name="is_level_not_daily",
            field=models.BooleanField(default=False),
        ),
    ]
