# Generated by Django 4.2.17 on 2026-07-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0134_well_is_level_not_daily"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="welllevelmeasurement",
            name="depth_unit",
        ),
        migrations.RemoveField(
            model_name="welllevelmeasurement",
            name="depth_value",
        ),
        migrations.RemoveField(
            model_name="wellyieldmeasurement",
            name="depth_unit",
        ),
        migrations.RemoveField(
            model_name="wellyieldmeasurement",
            name="depth_value",
        ),
    ]
