# Generated by Django 4.2.17 on 2026-08-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0135_remove_welllevelmeasurement_depth_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellcacheindicator",
            name="measurement_group_data_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when measurement group data generated. This is for file data of well.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wellcacheindicator",
            name="data_cache_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when data cache generated. This is for file data of well.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wellcacheindicator",
            name="metadata_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when metadata generated, this is for metadata of well, example: number_of_measurements_level.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WellMeasurementGroupData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_key", models.CharField()),
                ("measurement_type", models.CharField()),
                ("begin_measurement", models.DateTimeField(blank=True, null=True)),
                ("end_measurement", models.DateTimeField(blank=True, null=True)),
                ("number_of_measurements", models.PositiveIntegerField()),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gwml2.termmeasurementparameter",
                        verbose_name="Parameter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default Unit of measurement",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gwml2.unit",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gwml2.well"
                    ),
                ),
            ],
            options={
                "unique_together": {("well", "measurement_type", "parameter", "unit")},
            },
        ),
    ]
