# Generated by Django 4.2.17 on 2026-08-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0137_view_well"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitepreference",
            name="download_request_min_free_space_gb",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Minimum free space (in GB) that must remain on the download request storage (settings.MEDIA_ROOT). If the remaining space drops below this threshold, new download requests are temporarily blocked.",
            ),
        ),
    ]
