# Generated by Django 4.2.17 on 2026-09-21 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0138_sitepreference_download_request_min_free_space_gb"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSessionCheckpointLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkpoint",
                    models.IntegerField(
                        choices=[
                            (1, "Saving data"),
                            (2, "Cache wells"),
                            (3, "Cache country"),
                            (4, "Cache organisation"),
                            (5, "Create report"),
                            (6, "Finish"),
                        ]
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("finish_at", models.DateTimeField(blank=True, null=True)),
                (
                    "upload_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gwml2.uploadsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload session checkpoint log",
                "verbose_name_plural": "Upload session checkpoint logs",
                "db_table": "upload_session_checkpoint_log",
                "unique_together": {("upload_session", "checkpoint")},
            },
        ),
    ]
