# Generated by Django 4.2.17 on 2026-09-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwml2", "0139_uploadsessioncheckpointlog"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="uploadsessioncheckpointlog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="uploadsessioncheckpointlog",
            name="retry",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="uploadsessioncheckpointlog",
            name="step",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="uploadsessioncheckpointlog",
            unique_together={("upload_session", "checkpoint", "retry")},
        ),
    ]
