from gwml2.admin.construction import *
from gwml2.admin.drilling import *
from gwml2.admin.general import *
from gwml2.admin.geology import *
from gwml2.admin.hydrogeologic_parameters import *
from gwml2.admin.reference_elevation import *
from gwml2.admin.management import *
from gwml2.admin.term import *
from gwml2.admin.well import *
