# Generated by Django 2.2.12 on 2020-07-03 09:03

from abc import ABC

from django.db import migrations

from gwml2.migrations.sql.utils import load_sql


class ViewWellMigration(ABC, migrations.Migration):
    """View well migrations."""

    gwml_default = load_sql('gwml', 'default.sql')
    gwml_views = load_sql('gwml', 'views.sql')
    gwml_functions = load_sql('gwml', 'functions.sql')

    istsos_default = load_sql('istsos', 'default.sql')
    istsos_views = load_sql('istsos', 'views.sql')

    operations_defaults = [
        migrations.RunSQL(istsos_default, istsos_default),
        migrations.RunSQL(gwml_default, gwml_default),
    ]
    operations_creations = [
        migrations.RunSQL(gwml_views, gwml_default),
        migrations.RunSQL(gwml_functions, gwml_default),
        migrations.RunSQL(istsos_views, istsos_default)
    ]
    operations = operations_defaults + operations_creations
