# Generated by Django 2.2.12 on 2020-07-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0002_auto_20200701_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='GWLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_licence_id', models.CharField(help_text='Licence ID, e.g. a number.', max_length=150, verbose_name='gwLicenceID')),
                ('gw_purpose', models.TextField(help_text='Role of the licence.', verbose_name='gwPurpose')),
                ('gw_associated_gw_volume', models.FloatField(blank=True, help_text='Fluid volume associated with the licence.', null=True, verbose_name='gwAssociatedGWVolume')),
                ('gw_time_period', models.DateTimeField(blank=True, help_text='The period of time for which the licence is valid.', null=True, verbose_name='gwTimePeriod')),
            ],
        ),
        migrations.AddField(
            model_name='gwwell',
            name='gw_well_constructed_depth',
            field=models.OneToOneField(blank=True, help_text='Constructed depth of the well.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gw_well_constructed_depth', to='groundwater.Quantity', verbose_name='gwWellConstructedDepth'),
        ),
        migrations.AlterField(
            model_name='gwwell',
            name='gw_well_static_water_depth',
            field=models.OneToOneField(blank=True, help_text='Depth of the fluid body (e.g. piezometric level).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gw_well_static_water_depth', to='groundwater.Quantity', verbose_name='gwWellStaticWaterDepth'),
        ),
        migrations.AddField(
            model_name='gwwell',
            name='gw_well_licence',
            field=models.OneToOneField(blank=True, help_text='Licence relating to the drilling of the well or to the extraction of groundwater.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groundwater.GWLicence', verbose_name='gwWellLicence'),
        ),
    ]
