from gwml2.forms.well.casing import CasingForm
from gwml2.forms.uploader.csv_well_form import CsvWellForm
from gwml2.forms.well.construction import ConstructionForm
from gwml2.forms.well.document import DocumentForm
from gwml2.forms.well.drilling import DrillingForm
from gwml2.forms.well.general_information import GeneralInformationForm
from gwml2.forms.well.geology import GeologyForm
from gwml2.forms.well.stratigraphic_log import StratigraphicLogForm
from gwml2.forms.well.hydrogeology import HydrogeologyParameterForm
from gwml2.forms.well.pumping_test import PumpingTestForm
from gwml2.forms.well.license import LicenseForm
from gwml2.forms.well.management import ManagementForm
from gwml2.forms.well.measurement.level_measurement import WellGroundwaterLevelMeasurementForm
from gwml2.forms.well.measurement.quality_measurement import WellQualityMeasurementForm
from gwml2.forms.well.measurement.yield_measurement import WellYieldMeasurementForm
from gwml2.forms.well.reference_elevation import ReferenceElevationForm
from gwml2.forms.well.screen import ScreenForm
from gwml2.forms.well.water_strike import WaterStrikeForm
